export enum UNITY_PLAN_TYPE {
    UNITY_PLAN_TYPE_FLOOR = 0,
    UNITY_PLAN_TYPE_HIT_HORIZONTAL = 1,
    UNITY_PLAN_TYPE_HIT_VERTICAL = 2,
    UNITY_PLAN_TYPE_HIT_UNKNOWN = 3,
}

export enum SL_HEADING_STATE {
    SL_HEADING_STATE_GOOD = 0,
    SL_HEADING_STATE_OK = 1,
    SL_HEADING_STATE_NOT_GOOD = 2,
    SL_HEADING_STATE_NOT_CALIBRATED = 3,
    SL_HEADING_STATE_MAG_NOT_AVAILABLE = 4,
}

export enum SL_ERROR_CODE {
    SL_ERROR_CODE_SENSOR_CONFIGURATION_CHANGED = -6,
    SL_ERROR_CODE_POTENTIAL_CALIBRATION_ISSUE = -5,
    SL_ERROR_CODE_CONFIGURATION_FALLBACK = -4,
    SL_ERROR_CODE_SENSORS_DATA_REQUIRED = -3,
    SL_ERROR_CODE_CORRUPTED_FRAME = -2,
    SL_ERROR_CODE_CAMERA_REBOOTING = -1,
    SL_ERROR_CODE_SUCCESS = 0,
    SL_ERROR_CODE_FAILURE = 1,
    SL_ERROR_CODE_NO_GPU_COMPATIBLE = 2,
    SL_ERROR_CODE_NOT_ENOUGH_GPU_MEMORY = 3,
    SL_ERROR_CODE_CAMERA_NOT_DETECTED = 4,
    SL_ERROR_CODE_SENSORS_NOT_INITIALIZED = 5,
    SL_ERROR_CODE_SENSORS_NOT_AVAILABLE = 6,
    SL_ERROR_CODE_INVALID_RESOLUTION = 7,
    SL_ERROR_CODE_LOW_USB_BANDWIDTH = 8,
    SL_ERROR_CODE_CALIBRATION_FILE_NOT_AVAILABLE = 9,
    SL_ERROR_CODE_INVALID_CALIBRATION_FILE = 10,
    SL_ERROR_CODE_INVALID_SVO_FILE = 11,
    SL_ERROR_CODE_SVO_RECORDING_ERROR = 12,
    SL_ERROR_CODE_SVO_UNSUPPORTED_COMPRESSION = 13,
    SL_ERROR_CODE_END_OF_SVOFILE_REACHED = 14,
    SL_ERROR_CODE_INVALID_COORDINATE_SYSTEM = 15,
    SL_ERROR_CODE_INVALID_FIRMWARE = 16,
    SL_ERROR_CODE_INVALID_FUNCTION_PARAMETERS = 17,
    SL_ERROR_CODE_CUDA_ERROR = 18,
    SL_ERROR_CODE_CAMERA_NOT_INITIALIZED = 19,
    SL_ERROR_CODE_NVIDIA_DRIVER_OUT_OF_DATE = 20,
    SL_ERROR_CODE_INVALID_FUNCTION_CALL = 21,
    SL_ERROR_CODE_CORRUPTED_SDK_INSTALLATION = 22,
    SL_ERROR_CODE_INCOMPATIBLE_SDK_VERSION = 23,
    SL_ERROR_CODE_INVALID_AREA_FILE = 24,
    SL_ERROR_CODE_INCOMPATIBLE_AREA_FILE = 25,
    SL_ERROR_CODE_CAMERA_FAILED_TO_SETUP = 26,
    SL_ERROR_CODE_CAMERA_DETECTION_ISSUE = 27,
    SL_ERROR_CODE_CANNOT_START_CAMERA_STREAM = 28,
    SL_ERROR_CODE_NO_GPU_DETECTED = 29,
    SL_ERROR_CODE_PLANE_NOT_FOUND = 30,
    SL_ERROR_CODE_MODULE_NOT_COMPATIBLE_WITH_CAMERA = 31,
    SL_ERROR_CODE_MOTION_SENSORS_REQUIRED = 32,
    SL_ERROR_CODE_MODULE_NOT_COMPATIBLE_WITH_CUDA_VERSION = 33,
    SL_ERROR_CODE_DRIVER_FAILURE = 34,
    SL_ERROR_CODE_CAMERA_EXCEEDS_BANDWIDTH = 35,
}

export enum SL_RESOLUTION {
    SL_RESOLUTION_HD4K = 0,
    SL_RESOLUTION_QHDPLUS = 1,
    SL_RESOLUTION_HD2K = 2,
    SL_RESOLUTION_HD1536 = 3,
    SL_RESOLUTION_HD1080 = 4,
    SL_RESOLUTION_HD1200 = 5,
    SL_RESOLUTION_HD720 = 6,
    SL_RESOLUTION_SVGA = 7,
    SL_RESOLUTION_VGA = 8,
    SL_RESOLUTION_XVGA = 9,
    SL_RESOLUTION_TXGA = 10,
    SL_RESOLUTION_AUTO = 11,
}

export enum SL_UNIT {
    SL_UNIT_MILLIMETER = 0,
    SL_UNIT_CENTIMETER = 1,
    SL_UNIT_METER = 2,
    SL_UNIT_INCH = 3,
    SL_UNIT_FOOT = 4,
}

export enum SL_COORDINATE_SYSTEM {
    SL_COORDINATE_SYSTEM_IMAGE = 0,
    SL_COORDINATE_SYSTEM_LEFT_HANDED_Y_UP = 1,
    SL_COORDINATE_SYSTEM_RIGHT_HANDED_Y_UP = 2,
    SL_COORDINATE_SYSTEM_RIGHT_HANDED_Z_UP = 3,
    SL_COORDINATE_SYSTEM_LEFT_HANDED_Z_UP = 4,
    SL_COORDINATE_SYSTEM_RIGHT_HANDED_Z_UP_X_FWD = 5,
}

export enum SL_CAMERA_STATE {
    SL_CAMERA_STATE_AVAILABLE,
    SL_CAMERA_STATE_NOT_AVAILABLE,
}

export enum SL_MODEL {
    SL_MODEL_ZED = 0,
    SL_MODEL_ZED_M = 1,
    SL_MODEL_ZED2 = 2,
    SL_MODEL_ZED2i = 3,
    SL_MODEL_ZED_X = 4,
    SL_MODEL_ZED_XM = 5,
    SL_MODEL_ZED_X_HDR = 6,
    SL_MODEL_ZED_X_HDR_MINI = 7,
    SL_MODEL_ZED_X_HDR_MAX = 8,
    SL_MODEL_ZED_X_NANO = 9,
    SL_MODEL_VIRTUAL_ZED_X = 11,
    SL_MODEL_ZED_XONE_GS = 30,
    SL_MODEL_ZED_XONE_UHD = 31,
    SL_MODEL_ZED_XONE_HDR = 32,
}

export enum SL_MEM {
    SL_MEM_CPU = 0,
    SL_MEM_GPU = 1,
    SL_MEM_BOTH = 2,
}

export enum SL_BUS_TYPE {
    SL_BUS_TYPE_USB = 0,
    SL_BUS_TYPE_GMSL = 1,
    SL_BUS_TYPE_AUTO = 2,
}

export enum SL_SENSOR_TYPE {
    SL_SENSOR_TYPE_ACCELEROMETER = 0,
    SL_SENSOR_TYPE_GYROSCOPE = 1,
    SL_SENSOR_TYPE_MAGNETOMETER = 2,
    SL_SENSOR_TYPE_BAROMETER = 3,
}

export enum SL_SENSORS_UNIT {
    SL_SENSORS_UNIT_M_SEC_2 = 0,
    SL_SENSORS_UNIT_DEG_SEC = 1,
    SL_SENSORS_UNIT_U_T = 2,
    SL_SENSORS_UNIT_HPA = 3,
    SL_SENSORS_UNIT_CELSIUS = 4,
    SL_SENSORS_UNIT_HERTZ = 5,
}

export enum SL_SIDE {
    SL_SIDE_LEFT = 0,
    SL_SIDE_RIGHT = 1,
    SL_SIDE_BOTH = 2,
}

export enum SL_INPUT_TYPE {
    SL_INPUT_TYPE_USB = 0,
    SL_INPUT_TYPE_SVO = 1,
    SL_INPUT_TYPE_STREAM = 2,
    SL_INPUT_TYPE_GMSL = 3,
}

export enum SL_REFERENCE_FRAME {
    SL_REFERENCE_FRAME_WORLD = 0,
    SL_REFERENCE_FRAME_CAMERA = 1,
}

export enum SL_TIME_REFERENCE {
    SL_TIME_REFERENCE_IMAGE = 0,
    SL_TIME_REFERENCE_CURRENT = 1,
}

export enum SL_STREAMING_CODEC {
    SL_STREAMING_CODEC_H264 = 0,
    SL_STREAMING_CODEC_H265 = 1,
}

export enum SL_VIDEO_SETTINGS {
    SL_VIDEO_SETTINGS_BRIGHTNESS = 0,
    SL_VIDEO_SETTINGS_CONTRAST = 1,
    SL_VIDEO_SETTINGS_HUE = 2,
    SL_VIDEO_SETTINGS_SATURATION = 3,
    SL_VIDEO_SETTINGS_SHARPNESS = 4,
    SL_VIDEO_SETTINGS_GAMMA = 5,
    SL_VIDEO_SETTINGS_GAIN = 6,
    SL_VIDEO_SETTINGS_EXPOSURE = 7,
    SL_VIDEO_SETTINGS_AEC_AGC = 8,
    SL_VIDEO_SETTINGS_AEC_AGC_ROI = 9,
    SL_VIDEO_SETTINGS_WHITEBALANCE_TEMPERATURE = 10,
    SL_VIDEO_SETTINGS_WHITEBALANCE_AUTO = 11,
    SL_VIDEO_SETTINGS_LED_STATUS = 12,
    SL_VIDEO_SETTINGS_EXPOSURE_TIME = 13,
    SL_VIDEO_SETTINGS_ANALOG_GAIN = 14,
    SL_VIDEO_SETTINGS_DIGITAL_GAIN = 15,
    SL_VIDEO_SETTINGS_AUTO_EXPOSURE_TIME_RANGE = 16,
    SL_VIDEO_SETTINGS_AUTO_ANALOG_GAIN_RANGE = 17,
    SL_VIDEO_SETTINGS_AUTO_DIGITAL_GAIN_RANGE = 18,
    SL_VIDEO_SETTINGS_EXPOSURE_COMPENSATION = 19,
    SL_VIDEO_SETTINGS_DENOISING = 20,
    SL_VIDEO_SETTINGS_SCENE_ILLUMINANCE = 21,
    SL_VIDEO_SETTINGS_AE_ANTIBANDING = 22,
    SL_VIDEO_SETTINGS_LAST = 23,
}

export enum SL_SVO_ENCODING_PRESET {
    SL_SVO_ENCODING_PRESET_DEFAULT = 0,
    SL_SVO_ENCODING_PRESET_ULTRAFAST = 1,
    SL_SVO_ENCODING_PRESET_FAST = 2,
    SL_SVO_ENCODING_PRESET_MEDIUM = 3,
    SL_SVO_ENCODING_PRESET_SLOW = 4,
    SL_SVO_ENCODING_PRESET_LAST = 5,
}

export enum SL_TIMESTAMP_CLOCK {
    SL_TIMESTAMP_CLOCK_SYSTEM_CLOCK = 0,
    SL_TIMESTAMP_CLOCK_MONOTONIC_CLOCK = 1,
    SL_TIMESTAMP_CLOCK_LAST = 2,
}

export enum SL_VOXELIZATION_MODE {
    SL_VOXELIZATION_MODE_FIXED = 0,
    SL_VOXELIZATION_MODE_STEREO_UNCERTAINTY = 1,
    SL_VOXELIZATION_MODE_LINEAR = 2,
    SL_VOXELIZATION_MODE_LAST = 3,
}

export enum SL_MEASURE {
    SL_MEASURE_DISPARITY = 0,
    SL_MEASURE_DEPTH = 1,
    SL_MEASURE_CONFIDENCE = 2,
    SL_MEASURE_XYZ = 3,
    SL_MEASURE_XYZRGBA = 4,
    SL_MEASURE_XYZBGRA = 5,
    SL_MEASURE_XYZARGB = 6,
    SL_MEASURE_XYZABGR = 7,
    SL_MEASURE_NORMALS = 8,
    SL_MEASURE_DISPARITY_RIGHT = 9,
    SL_MEASURE_DEPTH_RIGHT = 10,
    SL_MEASURE_XYZ_RIGHT = 11,
    SL_MEASURE_XYZRGBA_RIGHT = 12,
    SL_MEASURE_XYZBGRA_RIGHT = 13,
    SL_MEASURE_XYZARGB_RIGHT = 14,
    SL_MEASURE_XYZABGR_RIGHT = 15,
    SL_MEASURE_NORMALS_RIGHT = 16,
    SL_MEASURE_DEPTH_U16_MM = 17,
    SL_MEASURE_DEPTH_U16_MM_RIGHT = 18,
}

export enum SL_VIEW {
    SL_VIEW_LEFT = 0,
    SL_VIEW_RIGHT = 1,
    SL_VIEW_LEFT_GRAY = 2,
    SL_VIEW_RIGHT_GRAY = 3,
    SL_VIEW_LEFT_NV12_UNRECTIFIED = 4,
    SL_VIEW_RIGHT_NV12_UNRECTIFIED = 5,
    SL_VIEW_LEFT_UNRECTIFIED = 6,
    SL_VIEW_RIGHT_UNRECTIFIED = 7,
    SL_VIEW_LEFT_UNRECTIFIED_GRAY = 8,
    SL_VIEW_RIGHT_UNRECTIFIED_GRAY = 9,
    SL_VIEW_SIDE_BY_SIDE = 10,
    SL_VIEW_DEPTH = 11,
    SL_VIEW_CONFIDENCE = 12,
    SL_VIEW_NORMALS = 13,
    SL_VIEW_DEPTH_RIGHT = 14,
    SL_VIEW_NORMALS_RIGHT = 15,
    SL_VIEW_LEFT_BGRA = 16,
    SL_VIEW_LEFT_BGR = 17,
    SL_VIEW_RIGHT_BGRA = 18,
    SL_VIEW_RIGHT_BGR = 19,
    SL_VIEW_LEFT_UNRECTIFIED_BGRA = 20,
    SL_VIEW_LEFT_UNRECTIFIED_BGR = 21,
    SL_VIEW_RIGHT_UNRECTIFIED_BGRA = 22,
    SL_VIEW_RIGHT_UNRECTIFIED_BGR = 23,
    SL_VIEW_SIDE_BY_SIDE_BGRA = 24,
    SL_VIEW_SIDE_BY_SIDE_BGR = 25,
    SL_VIEW_SIDE_BY_SIDE_GRAY = 26,
    SL_VIEW_SIDE_BY_SIDE_UNRECTIFIED_BGRA = 27,
    SL_VIEW_SIDE_BY_SIDE_UNRECTIFIED_BGR = 28,
    SL_VIEW_SIDE_BY_SIDE_UNRECTIFIED_GRAY = 29,
    SL_VIEW_DEPTH_BGRA = 30,
    SL_VIEW_DEPTH_BGR = 31,
    SL_VIEW_DEPTH_GRAY = 32,
    SL_VIEW_CONFIDENCE_BGRA = 33,
    SL_VIEW_CONFIDENCE_BGR = 34,
    SL_VIEW_CONFIDENCE_GRAY = 35,
    SL_VIEW_NORMALS_BGRA = 36,
    SL_VIEW_NORMALS_BGR = 37,
    SL_VIEW_NORMALS_GRAY = 38,
    SL_VIEW_DEPTH_RIGHT_BGRA = 39,
    SL_VIEW_DEPTH_RIGHT_BGR = 40,
    SL_VIEW_DEPTH_RIGHT_GRAY = 41,
    SL_VIEW_NORMALS_RIGHT_BGRA = 42,
    SL_VIEW_NORMALS_RIGHT_BGR = 43,
    SL_VIEW_NORMALS_RIGHT_GRAY = 44,
}

export enum SL_OBJECT_TRACKING_STATE {
    SL_OBJECT_TRACKING_STATE_OFF = 0,
    SL_OBJECT_TRACKING_STATE_OK = 1,
    SL_OBJECT_TRACKING_STATE_SEARCHING = 2,
    SL_OBJECT_TRACKING_STATE_TERMINATE = 3,
}

export enum SL_POSITIONAL_TRACKING_STATE {
    SL_POSITIONAL_TRACKING_STATE_SEARCHING = 0,
    SL_POSITIONAL_TRACKING_STATE_OK = 1,
    SL_POSITIONAL_TRACKING_STATE_OFF = 2,
    SL_POSITIONAL_TRACKING_STATE_FPS_TOO_LOW = 3,
    SL_POSITIONAL_TRACKING_STATE_SEARCHING_FLOOR_PLANE = 4,
    SL_POSITIONAL_TRACKING_STATE_UNAVAILABLE = 5,
}

export enum SL_ODOMETRY_STATUS {
    SL_ODOMETRY_STATUS_OK = 0,
    SL_ODOMETRY_STATUS_UNAVAILABLE = 1,
}

export enum SL_SPATIAL_MEMORY_STATUS {
    SL_MAP_TRACKING_STATUS_OK = 0,
    SL_MAP_TRACKING_STATUS_LOOP_CLOSED = 1,
    SL_MAP_TRACKING_STATUS_SEARCHING = 2,
    SL_MAP_TRACKING_STATUS_OFF = 3,
    SL_MAP_TRACKING_STATUS_INITIALIZING = 4,
    SL_MAP_TRACKING_STATUS_KNOWN_MAP = 5,
    SL_MAP_TRACKING_STATUS_MAP_UPDATE = 6,
    SL_MAP_TRACKING_STATUS_LOST = 7,
    SL_MAP_TRACKING_STATUS_NOT_ENOUGH_MEMORY_FOR_TRACKING = 8,
}

export enum SL_POSITIONAL_TRACKING_MODE {
    SL_POSITIONAL_TRACKING_MODE_GEN_1 = 0,
    SL_POSITIONAL_TRACKING_MODE_GEN_2 = 1,
    SL_POSITIONAL_TRACKING_MODE_GEN_3 = 2,
}

export enum SL_POSITIONAL_TRACKING_FUSION_STATUS {
    SL_POSITIONAL_TRACKING_FUSION_STATUS_VISUAL_INERTIAL = 0,
    SL_POSITIONAL_TRACKING_FUSION_STATUS_VISUAL = 1,
    SL_POSITIONAL_TRACKING_FUSION_STATUS_INERTIAL = 2,
    SL_POSITIONAL_TRACKING_FUSION_STATUS_GNSS = 3,
    SL_POSITIONAL_TRACKING_FUSION_STATUS_VISUAL_INERTIAL_GNSS = 4,
    SL_POSITIONAL_TRACKING_FUSION_STATUS_VISUAL_GNSS = 5,
    SL_POSITIONAL_TRACKING_FUSION_STATUS_INERTIAL_GNSS = 6,
    SL_POSITIONAL_TRACKING_FUSION_STATUS_UNAVAILABLE = 7,
}

export enum SL_REGION_OF_INTEREST_AUTO_DETECTION_STATE {
    SL_REGION_OF_INTEREST_AUTO_DETECTION_STATE_RUNNING = 0,
    SL_REGION_OF_INTEREST_AUTO_DETECTION_STATE_READY = 1,
    SL_REGION_OF_INTEREST_AUTO_DETECTION_STATE_NOT_ENABLED = 2,
}

export enum SL_AREA_EXPORTING_STATE {
    SL_AREA_EXPORTING_STATE_SUCCESS = 0,
    SL_AREA_EXPORTING_STATE_RUNNING = 1,
    SL_AREA_EXPORTING_STATE_NOT_STARTED = 2,
    SL_AREA_EXPORTING_STATE_FILE_EMPTY = 3,
    SL_AREA_EXPORTING_STATE_FILE_ERROR = 4,
    SL_AREA_EXPORTING_STATE_SPATIAL_MEMORY_DISABLED = 5,
}

export enum SL_SPATIAL_MAPPING_STATE {
    SL_SPATIAL_MAPPING_STATE_INITIALIZING = 0,
    SL_SPATIAL_MAPPING_STATE_OK = 1,
    SL_SPATIAL_MAPPING_STATE_NOT_ENOUGH_MEMORY = 2,
    SL_SPATIAL_MAPPING_STATE_NOT_ENABLED = 3,
    SL_SPATIAL_MAPPING_STATE_FPS_TOO_LOW = 4,
}

export enum SL_SPATIAL_MAP_TYPE {
    SL_SPATIAL_MAP_TYPE_MESH = 0,
    SL_SPATIAL_MAP_TYPE_FUSED_POINT_CLOUD = 1,
}

export enum SL_MESH_FILTER {
    SL_MESH_FILTER_LOW = 0,
    SL_MESH_FILTER_MEDIUM = 1,
    SL_MESH_FILTER_HIGH = 2,
}

export enum SL_MESH_FILE_FORMAT {
    SL_MESH_FILE_FORMAT_PLY = 0,
    SL_MESH_FILE_FORMAT_PLY_BIN = 1,
    SL_MESH_FILE_FORMAT_OBJ = 2,
}

export enum SL_DEPTH_MODE {
    SL_DEPTH_MODE_NONE = 0,
    SL_DEPTH_MODE_PERFORMANCE = 1,
    SL_DEPTH_MODE_QUALITY = 2,
    SL_DEPTH_MODE_ULTRA = 3,
    SL_DEPTH_MODE_NEURAL_LIGHT = 4,
    SL_DEPTH_MODE_NEURAL = 5,
    SL_DEPTH_MODE_NEURAL_PLUS = 6,
}

export enum SL_FLIP_MODE {
    SL_FLIP_MODE_OFF = 0,
    SL_FLIP_MODE_ON = 1,
    SL_FLIP_MODE_AUTO = 2,
}

export enum SL_COPY_TYPE {
    SL_COPY_TYPE_CPU_CPU = 0,
    SL_COPY_TYPE_CPU_GPU = 1,
    SL_COPY_TYPE_GPU_GPU = 2,
    SL_COPY_TYPE_GPU_CPU = 3,
}

export enum SL_SVO_COMPRESSION_MODE {
    SL_SVO_COMPRESSION_MODE_LOSSLESS = 0,
    SL_SVO_COMPRESSION_MODE_H264 = 1,
    SL_SVO_COMPRESSION_MODE_H265 = 2,
    SL_SVO_COMPRESSION_MODE_H264_LOSSLESS = 3,
    SL_SVO_COMPRESSION_MODE_H265_LOSSLESS = 4,
}

export enum SL_MAT_TYPE {
    SL_MAT_TYPE_F32_C1 = 0,
    SL_MAT_TYPE_F32_C2 = 1,
    SL_MAT_TYPE_F32_C3 = 2,
    SL_MAT_TYPE_F32_C4 = 3,
    SL_MAT_TYPE_U8_C1 = 4,
    SL_MAT_TYPE_U8_C2 = 5,
    SL_MAT_TYPE_U8_C3 = 6,
    SL_MAT_TYPE_U8_C4 = 7,
    SL_MAT_TYPE_U16_C1 = 8,
    SL_MAT_TYPE_S8_C4 = 9,
}

export enum SL_OBJECT_SUBCLASS {
    SL_OBJECT_SUBCLASS_PERSON = 0,
    SL_OBJECT_SUBCLASS_BICYCLE = 1,
    SL_OBJECT_SUBCLASS_CAR = 2,
    SL_OBJECT_SUBCLASS_MOTORBIKE = 3,
    SL_OBJECT_SUBCLASS_BUS = 4,
    SL_OBJECT_SUBCLASS_TRUCK = 5,
    SL_OBJECT_SUBCLASS_BOAT = 6,
    SL_OBJECT_SUBCLASS_BACKPACK = 7,
    SL_OBJECT_SUBCLASS_HANDBAG = 8,
    SL_OBJECT_SUBCLASS_SUITCASE = 9,
    SL_OBJECT_SUBCLASS_BIRD = 10,
    SL_OBJECT_SUBCLASS_CAT = 11,
    SL_OBJECT_SUBCLASS_DOG = 12,
    SL_OBJECT_SUBCLASS_HORSE = 13,
    SL_OBJECT_SUBCLASS_SHEEP = 14,
    SL_OBJECT_SUBCLASS_COW = 15,
    SL_OBJECT_SUBCLASS_CELLPHONE = 16,
    SL_OBJECT_SUBCLASS_LAPTOP = 17,
    SL_OBJECT_SUBCLASS_BANANA = 18,
    SL_OBJECT_SUBCLASS_APPLE = 19,
    SL_OBJECT_SUBCLASS_ORANGE = 20,
    SL_OBJECT_SUBCLASS_CARROT = 21,
    SL_OBJECT_SUBCLASS_PERSON_HEAD = 22,
    SL_OBJECT_SUBCLASS_SPORTSBALL = 23,
    SL_OBJECT_SUBCLASS_MACHINERY = 24,
    SL_OBJECT_SUBCLASS_LAST = 25,
}

export enum SL_OBJECT_ACTION_STATE {
    SL_OBJECT_ACTION_STATE_IDLE = 0,
    SL_OBJECT_ACTION_STATE_MOVING = 1,
}

export enum SL_OBJECT_DETECTION_MODEL {
    SL_OBJECT_DETECTION_MODEL_MULTI_CLASS_BOX_FAST = 0,
    SL_OBJECT_DETECTION_MODEL_MULTI_CLASS_BOX_MEDIUM = 1,
    SL_OBJECT_DETECTION_MODEL_MULTI_CLASS_BOX_ACCURATE = 2,
    SL_OBJECT_DETECTION_MODEL_PERSON_HEAD_BOX_FAST = 3,
    SL_OBJECT_DETECTION_MODEL_PERSON_HEAD_BOX_ACCURATE = 4,
    SL_OBJECT_DETECTION_MODEL_CUSTOM_BOX_OBJECTS = 5,
    SL_OBJECT_DETECTION_MODEL_CUSTOM_YOLOLIKE_BOX_OBJECTS = 6,
}

export enum SL_BODY_TRACKING_MODEL {
    SL_BODY_TRACKING_MODEL_HUMAN_BODY_FAST = 0,
    SL_BODY_TRACKING_MODEL_HUMAN_BODY_MEDIUM = 1,
    SL_BODY_TRACKING_MODEL_HUMAN_BODY_ACCURATE = 2,
}

export enum SL_AI_MODELS {
    SL_AI_MODELS_MULTI_CLASS_DETECTION = 0,
    SL_AI_MODELS_MULTI_CLASS_MEDIUM_DETECTION = 1,
    SL_AI_MODELS_MULTI_CLASS_ACCURATE_DETECTION = 2,
    SL_AI_MODELS_HUMAN_BODY_FAST_DETECTION = 3,
    SL_AI_MODELS_HUMAN_BODY_MEDIUM_DETECTION = 4,
    SL_AI_MODELS_HUMAN_BODY_ACCURATE_DETECTION = 5,
    SL_AI_MODELS_HUMAN_BODY_38_FAST_DETECTION = 6,
    SL_AI_MODELS_HUMAN_BODY_38_MEDIUM_DETECTION = 7,
    SL_AI_MODELS_HUMAN_BODY_38_ACCURATE_DETECTION = 8,
    SL_AI_MODELS_PERSON_HEAD_DETECTION = 9,
    SL_AI_MODELS_PERSON_HEAD_ACCURATE_DETECTION = 10,
    SL_AI_MODELS_REID_ASSOCIATION = 11,
    SL_AI_MODELS_NEURAL_LIGHT_DEPTH = 12,
    SL_AI_MODELS_NEURAL_DEPTH = 13,
    SL_AI_MODELS_NEURAL_PLUS_DEPTH = 14,
    SL_AI_MODELS_LAST = 15,
}

export enum SL_OBJECT_FILTERING_MODE {
    SL_OBJECT_FILTERING_MODE_NONE = 0,
    SL_OBJECT_FILTERING_MODE_NMS_3D = 1,
    SL_OBJECT_FILTERING_MODE_NMS_3D_PER_CLASS = 2,
}

export enum SL_OBJECT_ACCELERATION_PRESET {
    SL_OBJECT_ACCELERATION_PRESET_DEFAULT = 0,
    SL_OBJECT_ACCELERATION_PRESET_LOW = 1,
    SL_OBJECT_ACCELERATION_PRESET_MEDIUM = 2,
    SL_OBJECT_ACCELERATION_PRESET_HIGH = 3,
}

export enum SL_INFERENCE_PRECISION {
    SL_INFERENCE_PRECISION_FP32 = 0,
    SL_INFERENCE_PRECISION_FP16 = 1,
    SL_INFERENCE_PRECISION_INT8 = 2,
}

export enum SL_BODY_FORMAT {
    SL_BODY_FORMAT_BODY_18 = 0,
    SL_BODY_FORMAT_BODY_34 = 1,
    SL_BODY_FORMAT_BODY_38 = 2,
}

export enum SL_BODY_KEYPOINTS_SELECTION {
    SL_BODY_KEYPOINTS_SELECTION_FULL = 0,
    SL_BODY_KEYPOINTS_SELECTION_UPPER_BODY = 1,
}

export enum SL_BODY_18_PARTS {
    SL_BODY_18_PARTS_NOSE = 0,
    SL_BODY_18_PARTS_NECK = 1,
    SL_BODY_18_PARTS_RIGHT_SHOULDER = 2,
    SL_BODY_18_PARTS_RIGHT_ELBOW = 3,
    SL_BODY_18_PARTS_RIGHT_WRIST = 4,
    SL_BODY_18_PARTS_LEFT_SHOULDER = 5,
    SL_BODY_18_PARTS_LEFT_ELBOW = 6,
    SL_BODY_18_PARTS_LEFT_WRIST = 7,
    SL_BODY_18_PARTS_RIGHT_HIP = 8,
    SL_BODY_18_PARTS_RIGHT_KNEE = 9,
    SL_BODY_18_PARTS_RIGHT_ANKLE = 10,
    SL_BODY_18_PARTS_LEFT_HIP = 11,
    SL_BODY_18_PARTS_LEFT_KNEE = 12,
    SL_BODY_18_PARTS_LEFT_ANKLE = 13,
    SL_BODY_18_PARTS_RIGHT_EYE = 14,
    SL_BODY_18_PARTS_LEFT_EYE = 15,
    SL_BODY_18_PARTS_RIGHT_EAR = 16,
    SL_BODY_18_PARTS_LEFT_EAR = 17,
    SL_BODY_18_PARTS_LAST = 18,
}

export enum SL_BODY_34_PARTS {
    SL_BODY_34_PARTS_PELVIS = 0,
    SL_BODY_34_PARTS_NAVAL_SPINE = 1,
    SL_BODY_34_PARTS_CHEST_SPINE = 2,
    SL_BODY_34_PARTS_NECK = 3,
    SL_BODY_34_PARTS_LEFT_CLAVICLE = 4,
    SL_BODY_34_PARTS_LEFT_SHOULDER = 5,
    SL_BODY_34_PARTS_LEFT_ELBOW = 6,
    SL_BODY_34_PARTS_LEFT_WRIST = 7,
    SL_BODY_34_PARTS_LEFT_HAND = 8,
    SL_BODY_34_PARTS_LEFT_HANDTIP = 9,
    SL_BODY_34_PARTS_LEFT_THUMB = 10,
    SL_BODY_34_PARTS_RIGHT_CLAVICLE = 11,
    SL_BODY_34_PARTS_RIGHT_SHOULDER = 12,
    SL_BODY_34_PARTS_RIGHT_ELBOW = 13,
    SL_BODY_34_PARTS_RIGHT_WRIST = 14,
    SL_BODY_34_PARTS_RIGHT_HAND = 15,
    SL_BODY_34_PARTS_RIGHT_HANDTIP = 16,
    SL_BODY_34_PARTS_RIGHT_THUMB = 17,
    SL_BODY_34_PARTS_LEFT_HIP = 18,
    SL_BODY_34_PARTS_LEFT_KNEE = 19,
    SL_BODY_34_PARTS_LEFT_ANKLE = 20,
    SL_BODY_34_PARTS_LEFT_FOOT = 21,
    SL_BODY_34_PARTS_RIGHT_HIP = 22,
    SL_BODY_34_PARTS_RIGHT_KNEE = 23,
    SL_BODY_34_PARTS_RIGHT_ANKLE = 24,
    SL_BODY_34_PARTS_RIGHT_FOOT = 25,
    SL_BODY_34_PARTS_HEAD = 26,
    SL_BODY_34_PARTS_NOSE = 27,
    SL_BODY_34_PARTS_LEFT_EYE = 28,
    SL_BODY_34_PARTS_LEFT_EAR = 29,
    SL_BODY_34_PARTS_RIGHT_EYE = 30,
    SL_BODY_34_PARTS_RIGHT_EAR = 31,
    SL_BODY_34_PARTS_LEFT_HEEL = 32,
    SL_BODY_34_PARTS_RIGHT_HEEL = 33,
    SL_BODY_34_PARTS_LAST = 34,
}

export enum SL_BODY_38_PARTS {
    SL_BODY_38_PARTS_PELVIS = 0,
    SL_BODY_38_PARTS_SPINE_1 = 1,
    SL_BODY_38_PARTS_SPINE_2 = 2,
    SL_BODY_38_PARTS_SPINE_3 = 3,
    SL_BODY_38_PARTS_NECK = 4,
    SL_BODY_38_PARTS_NOSE = 5,
    SL_BODY_38_PARTS_LEFT_EYE = 6,
    SL_BODY_38_PARTS_RIGHT_EYE = 7,
    SL_BODY_38_PARTS_LEFT_EAR = 8,
    SL_BODY_38_PARTS_RIGHT_EAR = 9,
    SL_BODY_38_PARTS_LEFT_CLAVICLE = 10,
    SL_BODY_38_PARTS_RIGHT_CLAVICLE = 11,
    SL_BODY_38_PARTS_LEFT_SHOULDER = 12,
    SL_BODY_38_PARTS_RIGHT_SHOULDER = 13,
    SL_BODY_38_PARTS_LEFT_ELBOW = 14,
    SL_BODY_38_PARTS_RIGHT_ELBOW = 15,
    SL_BODY_38_PARTS_LEFT_WRIST = 16,
    SL_BODY_38_PARTS_RIGHT_WRIST = 17,
    SL_BODY_38_PARTS_LEFT_HIP = 18,
    SL_BODY_38_PARTS_RIGHT_HIP = 19,
    SL_BODY_38_PARTS_LEFT_KNEE = 20,
    SL_BODY_38_PARTS_RIGHT_KNEE = 21,
    SL_BODY_38_PARTS_LEFT_ANKLE = 22,
    SL_BODY_38_PARTS_RIGHT_ANKLE = 23,
    SL_BODY_38_PARTS_LEFT_BIG_TOE = 24,
    SL_BODY_38_PARTS_RIGHT_BIG_TOE = 25,
    SL_BODY_38_PARTS_LEFT_SMALL_TOE = 26,
    SL_BODY_38_PARTS_RIGHT_SMALL_TOE = 27,
    SL_BODY_38_PARTS_LEFT_HEEL = 28,
    SL_BODY_38_PARTS_RIGHT_HEEL = 29,
    // Hands
    SL_BODY_38_PARTS_LEFT_HAND_THUMB_4 = 30,
    SL_BODY_38_PARTS_RIGHT_HAND_THUMB_4 = 31,
    SL_BODY_38_PARTS_LEFT_HAND_INDEX_1 = 32,
    SL_BODY_38_PARTS_RIGHT_HAND_INDEX_1 = 33,
    SL_BODY_38_PARTS_LEFT_HAND_MIDDLE_4 = 34,
    SL_BODY_38_PARTS_RIGHT_HAND_MIDDLE_4 = 35,
    SL_BODY_38_PARTS_LEFT_HAND_PINKY_1 = 36,
    SL_BODY_38_PARTS_RIGHT_HAND_PINKY_1 = 37,
    SL_BODY_38_PARTS_LAST = 38,
}

export enum SL_MODULE {
    SL_MODULE_ALL = 0,
    SL_MODULE_DEPTH = 1,
    SL_MODULE_POSITIONAL_TRACKING = 2,
    SL_MODULE_OBJECT_DETECTION = 3,
    SL_MODULE_BODY_TRACKING = 4,
    SL_MODULE_SPATIAL_MAPPING = 5,
    SL_MODULE_LAST = 6,
}

export enum SL_POSITION_TYPE {
    SL_POSITION_TYPE_RAW = 0,
    SL_POSITION_TYPE_FUSION = 1,
}

export enum SL_OBJECT_CLASS {
    SL_OBJECT_CLASS_PERSON = 0,
    SL_OBJECT_CLASS_VEHICLE = 1,
    SL_OBJECT_CLASS_BAG = 2,
    SL_OBJECT_CLASS_ANIMAL = 3,
    SL_OBJECT_CLASS_ELECTRONICS = 4,
    SL_OBJECT_CLASS_FRUIT_VEGETABLE = 5,
    SL_OBJECT_CLASS_SPORT = 6,
    SL_OBJECT_CLASS_LAST = 7,
}

export enum SL_FUSION_ERROR_CODE {
    SL_FUSION_ERROR_CODE_FUSION_INCONSISTENT_FPS = -5,
    SL_FUSION_ERROR_CODE_FUSION_FPS_TOO_LOW = -4,
    SL_FUSION_ERROR_CODE_INVALID_TIMESTAMP = -3,
    SL_FUSION_ERROR_CODE_INVALID_COVARIANCE = -2,
    SL_FUSION_ERROR_CODE_NO_NEW_DATA_AVAILABLE = -1,
    SL_FUSION_ERROR_CODE_SUCCESS = 0,
    SL_FUSION_ERROR_CODE_GNSS_DATA_NEED_FIX = 1,
    SL_FUSION_ERROR_CODE_GNSS_DATA_COVARIANCE_MUST_VARY = 2,
    SL_FUSION_ERROR_CODE_BODY_FORMAT_MISMATCH = 3,
    SL_FUSION_ERROR_CODE_MODULE_NOT_ENABLED = 4,
    SL_FUSION_ERROR_CODE_SOURCE_MISMATCH = 5,
    SL_FUSION_ERROR_CODE_CONNECTION_TIMED_OUT = 6,
    SL_FUSION_ERROR_CODE_MEMORY_ALREADY_USED = 7,
    SL_FUSION_ERROR_CODE_INVALID_IP_ADDRESS = 8,
    SL_FUSION_ERROR_CODE_FAILURE = 9,
}

export enum SL_SENDER_ERROR_CODE {
    SL_SENDER_ERROR_CODE_GRAB_ERROR = -3,
    SL_SENDER_ERROR_CODE_INCONSISTENT_FPS = -2,
    SL_SENDER_ERROR_CODE_FPS_TOO_LOW = -1,
    SL_SENDER_ERROR_CODE_SUCCESS = 0,
    SL_SENDER_ERROR_CODE_DISCONNECTED = 1,
}

export enum SL_COMM_TYPE {
    SL_COMM_TYPE_LOCAL_NETWORK = 0,
    SL_COMM_TYPE_INTRA_PROCESS = 1,
}

export enum SL_GNSS_STATUS {
    SL_GNSS_STATUS_UNKNOWN = 0,
    SL_GNSS_STATUS_SINGLE = 1,
    SL_GNSS_STATUS_DGNSS = 2,
    SL_GNSS_STATUS_RTK_FIX = 3,
    SL_GNSS_STATUS_PPS = 5,
    SL_GNSS_STATUS_RTK_FLOAT = 4,
}

export enum SL_GNSS_MODE {
    SL_GNSS_MODE_UNKNOWN = 0,
    SL_GNSS_MODE_NO_FIX = 1,
    SL_GNSS_MODE_FIX_2D = 2,
    SL_GNSS_MODE_FIX_3D = 3,
}

export enum SL_GNSS_FUSION_STATUS {
    SL_GNSS_FUSION_STATUS_OK = 0,
    SL_GNSS_FUSION_STATUS_OFF = 1,
    SL_GNSS_FUSION_STATUS_CALIBRATION_IN_PROGRESS = 2,
    SL_GNSS_FUSION_STATUS_RECALIBRATION_IN_PROGRESS = 3,
}

export enum SL_FUSION_REFERENCE_FRAME {
    SL_FUSION_REFERENCE_FRAME_WORLD = 0,
    SL_FUSION_REFERENCE_FRAME_BASELINK = 1,
}
